### ISSUE TITLE
[Design] Implement in-disk indexes backend with rocksdb

### ISSUE THREAD

**Issue by jansegre** [HathorNetwork/hathor-core#332]
# Summary

This design describes basically how to add a new indexes backend in-disk using rocksdb besides our current in-memory backend.

# Motivation

The network is growing rapidly and the large number of transactions is increasing the memory usage of a full-node. It usually was enough to run a full-node with 8GB RAM, lately there have been cases with out-of-memory crashes with 8GB, so our recommendation increased to 16GB.

Secondarily, a full-node with an existing database will take a while (usually 10~50min) to start because no index is persisted and they have to be rebuilt on every start. Persisting the indexes across reboots will solve this really annoying behavior.

# Acceptance Criteria

- [ ] Have all indexes (except for the interval-tree ones, that will be removed with sync-v1) using the rocksdb backend by default
- [x] Initially make RocksDB indexes opt-in
- [x] Make sure the tests cover the new backend
- [ ] Persist the indexes across restarts (this can, and probably will, be implemented and released separately)

# Detailed explanation

## How to use rocksdb to persist indexes

Last July @msbrogli made a proof-of-concept implementation on #254 using rocksdb to persist the address-index(previously called wallet-index).

The main technique is using the sorted nature of rocksdb keys to implement queries that return sorted lists. This means that we can build the key such that when the key is are sorted, it also sorts the elements that we want to sort.

For example, the address-index sorts transactions by timestamp for each address, so the keys can be built as:

```
        key = [address][tx.timestamp][tx.hash]
              |--34b--||--4 bytes---||--32b--|
```

And then we iterate by `[address]` prefix and the keys will be sorted by (timestamp, hash) ([source](https://github.com/HathorNetwork/hathor-core/pull/254/files#diff-43ba4ce1c938bdda238c5751a95e43d7fe762507fd2db39382a9b4c22d3c88a1R145-R155)):

```python
    def _get_from_address_iter(self, address: str) -> Iterable[bytes]:
        self.log.debug('seek to', address=address)
        it = self._db.iterkeys(self._cf)
        it.seek(self._to_key(address))
        for _cf, key in it:
            addr, _, tx_hash = self._from_key(key)
            if addr != address:
                break
            self.log.debug('seek found', tx=tx_hash.hex())
            yield tx_hash
        self.log.debug('seek end')
```

## How to load persistent-indexes

The first implementation will simply reset all indexes when initializing (this is implemented by dropping the relevant column-families on rocksdb, which is an operation that has constant time `O(1)`), it's important to really make sure the index was successfully reset or fail initializing otherwise. This will still have the down-side of slow loading times but will significantly simplify the implementation and avoid introducing issues related to a change to the index initialization implementation.

The final solution will require the interval-tree indexes (which are all indexes that will not be ported to rocksdb) to support being rebuilt independently, that is without using the current loading machinery that relies on adding transactions to completely empty indexes. Once this is implemented "fast" loading can be enabled.

# Task break-down

- [x] Implement basic structure (cli-params, needed refactors, reset-on-initialize) to enable on-disk wallet-index (partially complete on the PoC PR): 0.5 dev days
- Port the following indexes (using the reset-on-initialize structure):
  - [x] tokens-index: 1 dev day
  - [x] block-index: 1 dev day
  - [x] mempool-tips-index: 1 dev day
  - [x] remove block-parents-index: 0.1 dev day
  - [ ] dependencies-indexes (rev/dir/txs): 1 dev day
- [ ] Detailed RAM measurement (before and after enabling indexes): 1 dev day
- [ ] Implement independent rebuild of interval-tree indexes and disable reset-on-initialize structure: 2 dev days

**Comment by msbrogli** [comment]
Here are my thoughts:

1) How to use rocksdb to persist indexes: Maybe add an example. When we query for a given prefix, we can easily navigate to the next/previous keys. Keys are ordered by prefix and a query is executed in O(log(n)).

2) Interval-tree rebuild: I didn't understand what you meant. In regard to rebuilding, we just need to move through the vertices in topological order and call the interval tree's add method.

3) It's not clear how much each index is using of RAM, and which part of the full node depends on each index.

4) Will we allow a full node to have on-memory indexes? Or just in-disk? If yes, when one or another are used?

**Comment by jansegre** [comment]
> Here are my thoughts:
> 
>     1. How to use rocksdb to persist indexes: Maybe add an example. When we query for a given prefix, we can easily navigate to the next/previous keys. Keys are ordered by prefix and a query is executed in O(log(n)).

I'll add an example. But we don't need to "navigate" the keys, we only need to iterate over the query result to build the resulting list that would be returned by the in-memory index.

>     2. Interval-tree rebuild: I didn't understand what you meant. In regard to rebuilding, we just need to move through the vertices in topological order and call the interval tree's add method.

Maybe it's the rebuild implementation is that simple. But currently the loading will call `add_to_indexes` and `del_to_indexes` which do a lot of little things in addition to just the interval-tree's add method, besides being intertwined with the wallet and token indexes. Outside of that the loading also updates all the other indexes, which will also need to be ported before we can fully disable reset-on-initialize.

>     3. It's not clear how much each index is using of RAM, and which part of the full node depends on each index.

Part of the design is measuring RAM usage impact. Maybe it could be extended to analyze the index usage _before_ having the in-disk implementation, but I don't think the extra work will have any impact, we will want to do this regardless, right?

As to what parts depend on which index, I think that could be useful but it's unclear to me how.

>     4. Will we allow a full node to have on-memory indexes? Or just in-disk? If yes, when one or another are used?

Yes, although I only mentioned on the Acceptance Criteria, I'll add this to the design. It might have a significant impact on testing (testing with an on-disk index, specially small tests, would probably get slower), but more important than running the tests is making sure the on-disk implementations work exactly like the current in-memory implementation, specially because any problem now would persist across restarts.

**Comment by pedroferreira1** [comment]
I like the design. I just have some questions:

1. When you say about the "first implementation" and "final solution" in the "How to load persistent-indexes" section, are we going to have more than one release with this feature?
2. As far as I understood the interval tree index will never go to disk, is that correct? We are going to keep it in memory until we remove the sync-v1, then it won't exist anymore, right? If that's the case I didn't understand the task "Implement independent rebuild of interval-tree indexes"
3. The first implementation release will have the option to keep all indexes in memory? If not we are making rocksdb required and not recommended like nowadays, right?

**Comment by jansegre** [comment]
> I like the design. I just have some questions:
> 
>     1. When you say about the "first implementation" and "final solution" in the "How to load persistent-indexes" section, are we going to have more than one release with this feature?

We _can_ have more than one release. The "first implementation" is a partial implementation of this design that can be deployed and reduce memory usage, although not speeding up the startup. But if the final implementation does not take too long to be implemented, we could very well release it together. But having a partial implementation that can be reviewed and merged independently seems like a great bonus to me.

>     2. As far as I understood the interval tree index will never go to disk, is that correct? We are going to keep it in memory until we remove the sync-v1, then it won't exist anymore, right? If that's the case I didn't understand the task "Implement independent rebuild of interval-tree indexes"

We don't know how long it will take before we can remove sync-v1. As long as we have interval-tree indexes, we need to be able to rebuild those indexes when initializing. Currently we have an initialization process that rebuilds all indexes at the same time and optionally fully validate, and all of that is relatively intertwined. When indexes are persisted we only need to rebuild the ones that aren't (namely interval-tree indexes), OR reset them all and use the current loading implementation (which is that the first version would do to keep working while we port all indexes).

>     3. The first implementation release will have the option to keep all indexes in memory? If not we are making rocksdb required and not recommended like nowadays, right?

Not only the first implementation, but at the end we would still have an option to keep memory indexes. I think it's useful to have in-memory indexes, at the very least for tests. But yeah, requiring rocksdb would prevent all tests that would use rocksdb instead of in-memory to run on Windows. I don't really know how to value of that versus only having to support rocksdb.

**Comment by pedroferreira1** [comment]
> But having a partial implementation that can be reviewed and merged independently seems like a great bonus to me.

Yes, totally agree.

> I think it's useful to have in-memory indexes, at the very least for tests.

I agree with you that having the possibility is good. We should see the work for that but I guess it's worth it.

The design looks good to me. It's approved.

**Comment by msbrogli** [comment]
@jansegre I understand the implementation is done and this design is to keep the docs updated. I feel that we should move it to a Markdown file somewhere (maybe RFCs or a `docs/` folder in hathor-core).

For the future, I feel that we should stop resetting the index every restart. We can easily serialize and deserialize the interval tree and make the node start in O(1). Before that, we must guarantee that the index is updated to the database. My solution to that is to mark the indexes as dirty when a new tx arrives and mark the indexes as updated when the new tx is processed. Besides that, we can generate a nonce and save in every independent database to double check files are not mixed. Regardless of this solution, we would need to have a cli command to clear the indexes and build them from scratch.

I feel that we should address my idea in a separate design so this one is complete.

**Comment by jansegre** [comment]
> @jansegre I understand the implementation is done and this design is to keep the docs updated. I feel that we should move it to a Markdown file somewhere (maybe RFCs or a `docs/` folder in hathor-core).

I think that would be great. I don't think this is design is complete enough to be an RFC, so I'm leaning more to put it on the `docs/` in hathor-core, even though it might not be that well maintained.

> For the future, I feel that we should stop resetting the index every restart. We can easily serialize and deserialize the interval tree and make the node start in O(1). Before that, we must guarantee that the index is updated to the database. My solution to that is to mark the indexes as dirty when a new tx arrives and mark the indexes as updated when the new tx is processed. Besides that, we can generate a nonce and save in every independent database to double check files are not mixed. Regardless of this solution, we would need to have a cli command to clear the indexes and build them from scratch.

I don't think it would be that easy to serialize/deserialize the interval-tree, for one it isn't pickable, and also, both operations wouldn't be `O(1)`, at the very least it would be `O(n)`, `n` being the size of the index.

We don't have the problem of mixing files because we're only using a single database. On the other hand we have optional indexes, so something like the nonce (maybe an "closed_at" timestamp) would be useful to know if we are starting with an optional index that wasn't enabled before.

> I feel that we should address my idea in a separate design so this one is complete.

I agree.

**Comment by jansegre** [comment]
Adding doc to the repo here: https://github.com/HathorNetwork/hathor-core/pull/375
