### ISSUE TITLE
[KTLO] CI build is broken again on macOS

### ISSUE THREAD

**Issue by jansegre** [HathorNetwork/hathor-core#384]
As noticed [on this build](https://github.com/HathorNetwork/hathor-core/actions/runs/2018097518).

Background: #379 

The issue we had previously was caused because the rocksdb version `6.28.2` was basically packaged with code from the `master` branch instead of from the `v6.28.2` tag, it is still unclear how that happened, it was probably a re-tag on the rocksdb repo, but that seems irrelevant now. The actual build issue was caused because the code on `master` had removed some deprecated headers that the `python-rocksdb` package that we depend on still uses. The practical solution for the KTLO last time, ended up being to just update the downstream rocksdb package on homebrew to a version that was just released. When that happened the correct code was used, which still had the deprecated headers.

The current issue is happening because rocksdb v7 was published and now officially removes the depracated headers that python-rocksdb relies on.

We are now left with the following options:

- not supporting rocksdb v7: this requires making sure we're only installing rocksdb versions lower than v7, it will at least make us need to directly compile it on macos builds (since homebrew does not keep packaged old versions), and will eventually require changes to the docker image build process too, when the rocksdb update eventually (actually it will already break the next nightly build) reaches the alpine repos (which wouldn't normally be a problem, but since the [rocksdb package](https://pkgs.alpinelinux.org/package/edge/testing/aarch64/rocksdb) is only found on the testing repos, there isn't and "old" stable version that we can use).
- supporting rocksdb v7, this will need updates to `python-rocksdb` but is hasn't been well maintained lately ([the last push](https://github.com/twmht/python-rocksdb/) was more than a year ago, and [the last release](https://pypi.org/project/python-rocksdb/#history) was more than 3 years ago), meaning it is very unlikely that we will get a PR merged and a new release anytime soon.

I propose that we fork `python-rocksdb` and maintain our own releases (probably under `python-rocksdb-hathor`), releasing a fix, and we can later release some improvements to it (there are several new rocksdb features that we could benefit from and also the project build structure could use some revamping, and also we could publish binary wheels which would greatly speedup installation for all cases: CI test runs, CI docker builds, development setups, standalone deploys, etc).

## Tasks

- [x] test a fullnode running for a while with the forked lib and rocksdb 7.0
- [x] revert a few changes on the fork that I've used that require newer rocksdb versions
- [x] also test our changes with older versions of rocksdb to make sure it won't break on deploys that don't use the docker image (for example Ubuntu 20.04, which is still quite popular, has rocksdb 5.17)
- [x] ~publish the forked library (including creating the public repo, pypi package, etc)~ no need to, we can just point to our github fork as a dependency instead of using a version from pypi
- [x] changing hathor-core to use our forked library

**Comment by jansegre** [comment]
I have a prototype working version of a fork of python-rocksdb that works with rocksdb 7.0, although I've used more up to date forks. But since I've removed some functionality it might still make sense to maintain our own fork with less functionality but compatible with a wider range of rocksdb versions. It has all the features that we're currently using.

**Comment by jansegre** [comment]
#385 has meen merged, this can be closed.
