### ISSUE TITLE
Effort to reduce memory usage of nodes in production

### ISSUE THREAD

**Issue by jansegre** [HathorNetwork/hathor-core#432]
# Summary

What initially started as a memory analysis to find out how we are using memory and what can be done to reduce memory consumption, became a validation for the current RocksDB indexes along with the new recommended configuration that we should use in production.

The new recommended configuration was deployed with the release of hathor-core v0.49.2 and looks very promising with the new measured memory usage dropping to ~4GB (from ~12GB). We should still keep an eye on this deploy, particularly for performance regressions, and then decide if we will stabilize and possibly change the default configuration.

# Motivation

Since the last round of investigations we have still been using memory indexes in production and memory usage has continued to grow, which was reaching about 12GB on our metrics. Because usage is still growing and it's closer and closer to the current 16GB we have on the current instances, we decided to make a new round of analysis.

# Investigation

There is a tool called [memray](https://github.com/bloomberg/memray) that was published recently that looks very
promising for our memory analysis, particularly because it claims to be able to track both native and python allocated
memory.

The main limitation of this tool is that it only works on Linux, which means it doesn't work on macOS, which I mainly
use. And on my Windows machine, I can run it under WSL, but I've had problems running long lasting tests. For those
reasons I've setup an instance on AWS to run the tests in.

The EC2 instance is a `z1d.large`, which appears to have the best single-core performance (which is our main
performance bottleneck), although even then it doesn't run quite as fast as on my M1 macOS machine, which is at least
interesting. I think we could make an instance performance comparison, maybe we have better performance on ARM, the
other promising instance to try would be `c7g.2xlarge` (which has enough RAM and the latest AWS ARM processor) it does have many more cores than we need, but there isn't a `r7g.large` instance yet, which could be the ideal alternative to compare agains `z1d.large`, but if `c7g.2xlarge` is not as fast, than `r7g.large` won't be too.

The first testing strategy was to run with both native and python allocation tracking on and analyse the results after
the node has been running for a while. However just the initialization phase, on the fastest configuration that we can
have would take at least around 30~40h to complete. And if there's anything wrong, new takes would take really long
too.

I've decided to experiment without native allocations tracking, which is probably not what will give us the results
that we want, but it's fast enough that the initialization takes less than 1h and can be re-tried many more times,
which is good for learning to use the tool better and could probably give some new insights in the meantime.

When syncing from scratch, a known problem started to appear when the sync reached around 20-01-2022, the problem is known and recoverable in a few ways (either it happens naturally but slowly, or manually which is quicker), however it continues to happen again periodically. This was known to happen only rarely, but it is possible the memory analysis itself is causing the problem to happen more frequently (for example, it could be having influence in a race condition). Because of this I haven't been able to complete a sync from scratch, I reached at most around 20-04-2022.

Somewhat influenced by the previous issue, I've restarted the node a few times to see what happens. I noticed that every time I restarted it, memory usage after initialization would be at a little less than 90% of what it was before restarting. This suggests that there is some accumulation of memory when the sync has been going on for a while.

One noticeable effect that the previous issue has is spamming the logs with warning messages. It could be that the logging mechanism itself is the cause of lag or that the logging mechanism is either buffering (as in a buffer is created and increased, but not decreased) or leaking memory in a way that accumulates memory usage over time. I'll test commenting out the logging of that issue and check how it affects memory usage.

Experimenting with the logs (disabling the most verbose logs), didn't seem to have any noticeable impact on memory usage. However it did seem to affect the chance of the sync issue mentioned above from happening. But since it didn't seem to affect memory usage, I stopped experimenting with the logs.

Before shutting down the instance which is being used for tests I wanted to use the machine for some final tests, which are basically collecting a full memray report when syncing from a checkpoint and also when syncing from scratch. So far the first case has been running for a little over 24h and seems like it will need about ~50h more, the second test will probably take even longer (it could be affected by the sync problem that was noticed).

### Cache memory usage estimate

Contents of `~/hathor-nodes/data-2/env`:

```
export HATHOR_DATA=$LOCAL_DATA
export HATHOR_PEER=$LOCAL_DATA/peer.json

# common
export HATHOR_EXPORT_FILE=$LOCAL_DATA/../hathor-export.bin
export HATHOR_IMPORT_FILE=$LOCAL_DATA/../hathor-export.bin
export HATHOR_X_ROCKSDB_INDEXES=true
export HATHOR_WALLET_INDEX=true
export HATHOR_UTXO_INDEX=true
export HATHOR_CACHE=true
export HATHOR_CACHE_SIZE=100
export HATHOR_RECURSION_LIMIT=10000
export HATHOR_HOST=localhost
export HATHOR_ENABLE_DEBUG_API=true

# specific
export HATHOR_LISTEN=tcp:9002
export HATHOR_STATUS=9082
export HATHOR_BOOTSTRAP=tcp://127.0.0.1:9003
```

Contents of `~/hathor-core/htrmain2_memray.sh`:

```
#!/bin/bash

LOCAL_DATA=$HATHOR_NODES/data-2

if [ ! -d $LOCAL_DATA ]
then
        echo \"$LOCAL_DATA\" not found
        exit 1
fi

# add LOCAL_DATA to PYTHONPATH so we can load the settings
export PYTHONPATH=$LOCAL_DATA
export HATHOR_CONFIG_FILE=conf

ENV_FILE=$LOCAL_DATA/env
source $ENV_FILE
exec poetry run memray run --trace-python-allocators --live-remote -m hathor $@
```

The current test was made on the `dev` branch at `3af02c4d078adde5adffb79d9ccb727d5f0cadab`. Basically by running `./htrmain2_memray.sh shell` and then the following sequence of commands inside the shell, while recording the some of the live metrics from another shell (memray will print the command that has to be run to watch the metrics).

This is the sequence of memory usage recorded and the commands that were run inside the shell:

```
Current heap size:   4.007GB
Max heap size seen:  4.007GB
```

```python
manager.start()
len(tx_storage.cache)
```

```
Current heap size:   8.423GB
Max heap size seen:  8.423GB
```

```python
def fill_cache():
    for tx in tx_storage.topological_iterator():
        if len(tx_storage.cache) >= tx_storage.capacity:
            break
    else:
        print('fell through')

tx_storage.set_capacity(10_000)
fill_cache()
```

```
Current heap size:   8.448GB
Max heap size seen:  8.448GB
```

```python
tx_storage.set_capacity(100_000)
fill_cache()
```

```
Current heap size:   8.809GB
Max heap size seen:  8.809GB
```

```python
tx_storage.set_capacity(1_000_000)
fill_cache()
```

```
Current heap size:  12.133GB
Max heap size seen: 12.133GB
```
                                                                                                                                                                                                                                                                                
```python
tx_storage.set_capacity(2_000_000)
fill_cache()
```

```
Current heap size:  16.213GB
Max heap size seen: 16.213GB
```
                                                      
```python
tx_storage.set_capacity(1_000_000)
```

```
Current heap size:  12.656GB
Max heap size seen: 16.213GB
```
                                                             
```python
tx_storage.set_capacity(100_000)                    
```

```
Current heap size:  9.057GB
Max heap size seen: 16.213GB
```
                                                             
```python
tx_storage.set_capacity(10_000)
```

```
Current heap size:  8.728GB
Max heap size seen: 16.213GB
```
                                                             
```python
tx_storage.set_capacity(0)
```

```
Current heap size:  8.693GB
Max heap size seen: 16.213GB
```

Comparing the heap size increase per cached tx for each scenario we have (sizes are in bytes):

| txs     | heap size   | heap size incr. | incr per tx |
|---------|-------------|-----------------|-------------|
|   10000 |  8448000000 |        25000000 |        2500 |
|  100000 |  8809000000 |       386000000 |        3860 |
| 1000000 | 12133000000 |      3710000000 |        3710 |
| 2000000 | 16213000000 |      7790000000 |        3895 |
| 1000000 | 12656000000 |      4233000000 |        4233 |
|  100000 |  9057000000 |       634000000 |        6340 |
|   10000 |  8728000000 |       305000000 |       30500 |

The heap size after freezing seems to have some bias, maybe there are lingering objects that haven't been freed, still taking space on the heap. The size per tx on low caches is a bit smaller on lower cache capacities, so maybe there is some negative bias (some txs could still be in memory and not have been collected from the initialization phase), which would be taking heap size space on the base heap size which is subtracted from all.

Either way, it seems that for large capacities it approaches to around 4KB/tx, which looks like a decent rule of thumb for predicting memory usage for a given cache size.

## Methodology

### Environment

- instance: `z1d.large`, which has 2 CPUs (x86_64, intel), 16GB RAM,
- `uname -a`: `Linux hathor-core-dev 5.15.0-1017-aws #21-Ubuntu SMP Fri Aug 5 11:10:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- `python -VV`: `Python 3.10.5 (main, Jul 12 2022, 17:53:55) [GCC 11.2.0]`
- main snapshot used was `rocksdb-index-enabled-data-20220719-123425.tar.gz`

## Findings

- ~Using the cache storage doesn't seem worth it when using RocksDB indexes (it's still good for initialization when using memory indexes);~ (Cache storage does make a noticeable difference for several queries, but has a very low hit rate during initialization, we already deployed a patch that disables cache during initialization and it solved this issue, using cache is still recommended)
- Extra memory consumption for using cache can be estimated by `capacity * 4KB`, for example, a cache with size of 1_000_000 takes `~4GB` of extra memory, and a cache of 100_000 takes `~400MB` of extra memory, and so on;
- RocksDB indexes don't seem to have a noticeable impact on runtime performance anymore (which wasn't the case when it was first released);
- Currently, when using the settings that optimize memory use the most, and also considering the current database size, memory usage is consistently around 8GB (some variation still happens and is still unknown where it comes from, but apparently when syncing from scratch the total memory used is slightly higher than when starting with the same synced database), this isn't nearly enough to reduce the RAM recommendation, but it's looking much better than the ~12GB or more that we're seeing with memory indexes;
- RocksDB automatically uses memory structures to speedup many operations and, for the current database, it seems to be around 3.7GB though it's still unknown how it varies with the database size or how we can optimize it;
- We noticed that the RAM usage metric that was previously at around 12GB, is now at around 4GB, which is almost half of what was measured with memray (around 8GB). After some investigation it looks like this is because RocksDB uses mmap to map its files to memory, to memray the "memory allocated" by mmap counts as regular memory being used, but on the other hand Linux ends up not actually using a significant amount of RAM; (PS: after over a month the node was using between 5~6GB RAM on version v0.50.2 and a week later it was using 6~8GB on v0.51.0 most likely because of some changes that were introduced)

# Tasks

- [x] Deploy new nodes with recommended optimized settings to reduce memory usage;
- [x] Monitor and revisit the deploy above to re-asses the experimental status of `--x-rocksdb-index` and possibly make it the default;
  - Week 0: all hosts started with about 4.43GB of used RAM with very little variation;
  - Week 1: usage is about 4.83GB on average, ranging from 4.59GB to 5.15GB, no performance regressions or new bugs seem to have appeared;
  - Week 2: usage is about 4.88GB on average, ranging from 4.60GB to 5.18GB, there's a possible bug found but the impact is very minimal so a new release will not be rushed, also there has been very little change the last week, which is a sign that usage has stabilized, even though we don't know where the increase in the first week came from;
  - Week 3: usage is about 4.92GB on average, ranging from 4.68GB to 5.23GB, no new bugs have been found, increase in usage is still very small, it is similar to the increase from Week 1 to Week 2, so this might be an indicator that it is actually increasing but very very little (less than 50MB per week, which would be less than 2.6GB per year, which is absolutely great);
  - Week 4: usage is about 5.26GB on average, ranging from 4.80GB to 5.74GB, we noticed an issue with the sync but it happens on older versions so it wasn't introduced by the memory reduction, this last week memory usage grew much more than the last two, growth was similar to Week 1's, it also coincided with the week several new deploys were started and stopped, so there's a good chance it's related;
  - Week 4b: in turn the stats for the new deploy launched last week (v0.50.0) with 100k cache (an extra ~413MB of RAM usage) are about 5.07GB on average, ranging from 4.97GB to 5.14GB, which corrected to what usage would be without cache would be 4.66GB on average, ranging from 4.56GB to 4.73GB, which would be less than what is was on Week 1, it's possible that the cache helps prevent hitting the db in a way which would increase memory usage because of the mmap, so the correction may not be too accurate, but even without it usage is much better than Week 4's and more in line with what we would expect Week 4 to be following the trend from Weeks 1 to 3;
- [x] Finish collecting memray metrics from "load from snapshot" run;
  - the node finished loading by Saturday (30-07), but it couldn't sync any blocks/txs for more than 24h, I stopped the node because it didn't seem it was going to make any progress, the collected dump has 19GB, I still have some subtasks to do
  - [x] put a copy of the analysis file on an S3 bucket [0.1 dev days]
  - [x] generate memray reports [0.1 dev days]
- [ ] ~Finish collecting memray metrics from "sync from scratch" run;~ Cancelled because it never really finished loading

# Conclusion

After defaults were changed and some bugs were fixed, memory usage dropped from an average of 12GB to around 8GB (possibly less in some cases), while still having cache enabled normally and comparable performance.

**Comment by jansegre** [comment]
It would be great to have a review from @msbrogli and @luislhl on this.

**Comment by luislhl** [comment]
> Week 1: usage is about 4.83GB on average, ranging from 4.59GB to 5.15GB, no performance regressions or new bugs seem to have appeared;

Do you have some idea on what causes this increase after 1 week?

Maybe RocksDB needed to access part of the files that were `mmap`ed?

---

Overrall I think you did great progress, so :heavy_check_mark: from me

**Comment by jansegre** [comment]
> > Week 1: usage is about 4.83GB on average, ranging from 4.59GB to 5.15GB, no performance regressions or new bugs seem to have appeared;
> 
> Do you have some idea on what causes this increase after 1 week?
> 
> Maybe RocksDB needed to access part of the files that were `mmap`ed?

I didn't think too much about it, but I also suspect I could be related to the `mmap`ed file. When I measure it again I'll check if I can measure this without affecting the node.

**Comment by msbrogli** [comment]
Hi @jansegre . Here are my thoughts and questions:

1. What Python version was used for these tests? May the Python version affect the analysis?

2. What OS and Kernel version were used for these tests? Maybe the libc or any other library might affect the results?

3. Which snapshot was used for testing? Did we synced with the mainnet? How many transactions in total? What was the best block's height during the tests? I feel these pieces of information are important so we can compare future results with the ones presented here.

4. > Using the cache storage doesn't seem worth it when using RocksDB indexes (it's still good for initialization when using memory indexes);

Why? How does the indexes affect the hit rate of the cache storage?

5. Where does the 4.13KB constant come from? Does it include the metadata?

6. Some findings say that the full node is currently using 8GB but others say 4GB. I imagine these tests had different setups, right? Can you provide more information about these setups?

I feel the report is descriptive information about the test itself, including number of CPU, RAM, storage, kernel version, Python version, AWS instance, AWS region, Blockchain best block's height and number of transactions, date and time of the beginning and end of each test, overall setup of each test. These pieces of information would help me to review the methodology and the conclusions of each performed test.

**Comment by jansegre** [comment]
> Hi @jansegre . Here are my thoughts and questions:
> 
>   1. What Python version was used for these tests? May the Python version affect the analysis?
> 

Python 3.10.5, I added this with more details to the Environment section.

>   2. What OS and Kernel version were used for these tests? Maybe the libc or any other library might affect the results?
> 

Basically the Ubuntu 22.04 provided by AWS, I added more details to the Environment section.

>   3. Which snapshot was used for testing? Did we synced with the mainnet? How many transactions in total? What was the best block's height during the tests? I feel these pieces of information are important so we can compare future results with the ones presented here.
> 

`rocksdb-index-enabled-data-20220719-123425.tar.gz`, also added to the Environment section.

>   4. > Using the cache storage doesn't seem worth it when using RocksDB indexes (it's still good for initialization when using memory indexes);
>  
>   Why? How does the indexes affect the hit rate of the cache storage?
> 

I retracted that, and left a comment with more details. It's not that the indexes affect the hit rate, but more that depending on how we initialize, the hit rate is really low, the initialization method we used a while ago used to went through all transactions at least twice, which for a high enough cache guarantees a hit rate of at least 50%, but the currant main initialization is much more efficient in how the tx's are loaded, which makes the cache use much less efficient.

>   5. Where does the 4.13KB constant come from? Does it include the metadata?
> 

Unfortunately I don't have the results for this saved anywhere, I'm currently re-running the tests that gave those results to have them documented.

>   6. Some findings say that the full node is currently using 8GB but others say 4GB. I imagine these tests had different setups, right? Can you provide more information about these setups?
> 

This is basically explained here:

```
- We noticed that the RAM usage metric that was previously at around 12GB, is now at around 4GB, which is almost half of what was measured with memray (around 8GB). After some investigation it looks like this is because RocksDB uses mmap to map its files to memory, to memray the "memory allocated" by mmap counts as regular memory being used, but on the other hand Linux ends up not actually using a significant amount of RAM;
```

> I feel the report is missing descriptive information about the tests themselves, including number of CPU, RAM, storage, kernel version, Python version, AWS instance, AWS region, Blockchain best block's height and number of transactions, date and time of the beginning and end of each test, overall setup of each test. These pieces of information would help me to review the methodology and the conclusions of each performed test.

I agree. I added most of these descriptive details that I could recover.

**Comment by luislhl** [comment]
> We noticed that the RAM usage metric that was previously at around 12GB, is now at around 4GB.

Is this still true? I think our current fullnodes (v0.51.0) are reporting usage of around 8 GB on Grafana.

Maybe you should highlight in what conditions we get the 4 GB usage

---

I think we could have a "conclusion" session with a summary of what we have achieved in the issue.

Something like: "we were able to reduce memory usage by X GB when using RocksDB indices, and we should still use cache because it helps in the performance of some APIs"

**Comment by msbrogli** [comment]
@jansegre Thanks for the extra information about your setup. I feel we will get back to memory analysis later and this report will be valuable.

I like the idea of a "Conclusion" session with the lessons learned (including about using the tools).

Anyway, this report is approved by me.

**Comment by jansegre** [comment]
Oh, to me "Findings" was the conclusion. But I'll add a Conclusion section with a summary.


> > We noticed that the RAM usage metric that was previously at around 12GB, is now at around 4GB.
> 
> Is this still true? I think our current fullnodes (v0.51.0) are reporting usage of around 8 GB on Grafana.
> 
> Maybe you should highlight in what conditions we get the 4 GB usage

I'll add one, but I think some recent features could have caused a memory usage increase. It was between 5~6 right before the last deploy if I remember correctly.

**Comment by msbrogli** [comment]
The conclusion seems good to me. Approved!

**Comment by luislhl** [comment]
Approved!
